# Generated by Django 5.1.2 on 2025-02-05 14:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0007_alter_tarefa_prazo"),
    ]

    operations = [
        migrations.AlterField(
            model_name="tarefa",
            name="prazo",
            field=models.DateField(),
        ),
    ]
