# Generated by Django 5.1.2 on 2025-02-05 21:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0008_alter_tarefa_prazo"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="tarefa",
            name="categoria",
        ),
        migrations.AddField(
            model_name="tarefa",
            name="categorias",
            field=models.ManyToManyField(related_name="tarefas", to="core.categoria"),
        ),
    ]
